package org.fairc.forwardcheck;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.provider.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;

/** A small home/settings screen; automatic warnings stay over the messaging app. */
public final class MainActivity extends Activity {
    public static final String EXTRA_TEXT="message_text",EXTRA_SOURCE="message_source";
    private AppPrefs prefs;private Ui ui;private TextView status,mark;private Button background;private boolean settingUp;
    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);prefs=new AppPrefs(this);ui=new Ui(this);if(!getSharedPreferences("ui_language",MODE_PRIVATE).getBoolean("setup_complete",false))setupLanguage();else{home();receive(getIntent());}}
    @Override public void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(!settingUp)receive(intent);}
    @Override public void onResume(){super.onResume();refresh();}
    private void setupLanguage(){
        settingUp=true;LinearLayout box=ui.column();TextView brand=ui.title("Verity");brand.setGravity(Gravity.CENTER);brand.setLayoutParams(new LinearLayout.LayoutParams(-1,-2));box.addView(brand);LinearLayout card=ui.card();card.addView(ui.text("App language",26));
        RadioGroup choices=new RadioGroup(this);RadioButton english=new RadioButton(this),hindi=new RadioButton(this);english.setId(View.generateViewId());hindi.setId(View.generateViewId());english.setText("English");hindi.setText("हिन्दी");english.setTextSize(23);hindi.setTextSize(23);english.setMinHeight(ui.dp(56));hindi.setMinHeight(ui.dp(56));choices.addView(english);choices.addView(hindi);choices.check("hi".equals(I18n.language(this))?hindi.getId():english.getId());
        card.addView(choices);card.addView(ui.note("Messages in English and Hindi are checked in either language."));box.addView(card);Button next=ui.button("Continue",true);next.setOnClickListener(v->{I18n.setLanguage(this,choices.getCheckedRadioButtonId()==hindi.getId()?"hi":"en");settingUp=false;home();receive(getIntent());});box.addView(next);setContentView(ui.screen(box));
    }
    private void home(){LinearLayout box=ui.column();TextView brand=ui.title("Verity");brand.setGravity(Gravity.CENTER);brand.setLayoutParams(new LinearLayout.LayoutParams(-1,-2));box.addView(brand);LinearLayout state=ui.card();state.setGravity(Gravity.CENTER_HORIZONTAL);mark=ui.mark("✓",Ui.GREEN);state.addView(mark);status=ui.text("",23);status.setGravity(Gravity.CENTER);status.setTypeface(null,android.graphics.Typeface.BOLD);state.addView(status);box.addView(state);
        background=ui.button("Keep checks on",true);background.setOnClickListener(v->BackgroundSetup.request(this));box.addView(background);
        Button paste=ui.button("Check a message",true);paste.setOnClickListener(v->paste());box.addView(paste);
        Button photo=ui.button("Check a picture",false);photo.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),12));box.addView(photo);
        LinearLayout menu=ui.card();Button last=ui.menuLink("Last check");last.setOnClickListener(v->latest());menu.addView(last);menu.addView(ui.divider());
        // SOCIAL SCREENING: owned by the social feature task; preserve this entry.
        Button social=ui.menuLink("Social media");social.setOnClickListener(v->startActivity(new Intent(this,org.fairc.forwardcheck.social.SocialSettingsActivity.class)));menu.addView(social);menu.addView(ui.divider());
        // END SOCIAL SCREENING
        Button settings=ui.menuLink("Settings");settings.setOnClickListener(v->settings());menu.addView(settings);box.addView(menu);setContentView(ui.screen(box));refresh();}
    private void refresh(){if(status==null)return;boolean key=prefs.paired(),sms=SmsPrefs.enabled(this)&&SmsPrefs.contactsAllowed(this),helper=ForwardAccessibilityService.helperConnected(),allowed=BackgroundSetup.allowed(this),configured=key||sms,ready=configured&&helper&&allowed;String readyText=sms?(key?"Ready\nOpen WhatsApp or Messages.":"Ready\nOpen Messages."):"Ready\nOpen WhatsApp.";status.setText(I18n.text(this,!configured?"One-time setup\nAdd your checking key in Settings.":!helper?"Turn on the helper\nOpen Settings to get started.":!allowed?"One more step\nTap Keep checks on.":readyText));ui.styleMark(mark,ready?"✓":"!",ready?Ui.GREEN:Ui.AMBER);if(background!=null)background.setVisibility(configured&&helper&&!allowed?View.VISIBLE:View.GONE);}
    private void paste(){EditText input=new EditText(this);input.setHint(I18n.text(this,"Paste or type a message"));input.setTextSize(21);input.setMinLines(3);input.setSaveEnabled(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);
        AlertDialog d=I18n.dialog(this).setTitle("Check a message").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Continue",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String text=input.getText().toString().trim();if(text.length()<3){input.setError(I18n.text(this,"Add a message first."));return;}startActivity(new Intent(this,ConsentActivity.class).putExtra(EXTRA_TEXT,text).putExtra(EXTRA_SOURCE,"manual"));input.setText("");d.dismiss();}));d.show();}
    private void settings(){String[] labels={"Message helper","People to check","Checking key","Costs","How it works","Language","SMS scam warnings"},options=new String[labels.length];for(int i=0;i<labels.length;i++)options[i]=I18n.text(this,labels[i]);I18n.dialog(this).setTitle("Settings").setItems(options,(d,i)->{if(i==0)startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));else if(i==1)contacts();else if(i==2)key();else if(i==3)costs();else if(i==5)language();else if(i==6)startActivity(new Intent(this,SmsSettingsActivity.class));else I18n.dialog(this).setTitle("How it works").setMessage("Open a WhatsApp chat. The helper screens forwards, messages from unknown numbers, and people you choose.\n\nIt reads text and pictures on your phone. Tap Check to send only that message's text to DeepSeek through OpenRouter. Wi-Fi or mobile data is needed for the answer.\n\nTap Not now or Close to stop alerts for that message. A new copy can be checked again.\n\nAI picture detection is experimental. Missing watermarks do not prove a picture is real.").setPositiveButton("Done",null).show();}).setNegativeButton("Done",null).show();}
    private void key(){EditText input=new EditText(this);input.setHint("OpenRouter key");input.setContentDescription("OpenRouter key");input.setSingleLine(true);input.setSaveEnabled(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);AlertDialog d=I18n.dialog(this).setTitle("Checking key").setMessage(prefs.paired()?"A key is saved on this phone. Enter a new one to replace it.":"Saved on this phone. No computer needed.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->{d.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);d.getButton(-1).setOnClickListener(v->{try{prefs.setApiKey(input.getText().toString());input.setText("");d.dismiss();refresh();}catch(Exception e){input.setError(I18n.text(this,"Please enter a valid key."));}});});d.show();}
    private void contacts(){ChosenContacts c=new ChosenContacts(this);JSONArray rows=c.rows();String[] options=new String[rows.length()+1];options[0]=I18n.text(this,"Add a person");for(int i=0;i<rows.length();i++)options[i+1]=rows.optJSONObject(i).optString("name");
        new AlertDialog.Builder(this).setTitle(I18n.text(this,"People to check")).setItems(options,(d,i)->{if(i==0){try{startActivityForResult(new Intent(Intent.ACTION_PICK,ContactsContract.CommonDataKinds.Phone.CONTENT_URI),11);}catch(Exception e){Toast.makeText(this,I18n.text(this,"Could not open contacts."),Toast.LENGTH_LONG).show();}}else I18n.dialog(this).setTitle("Stop checking this person?").setNegativeButton("Keep",null).setPositiveButton("Remove",(x,w)->{c.remove(i-1);contacts();}).show();}).setNegativeButton("Done",null).show();}
    private void language(){I18n.dialog(this).setTitle("App language").setItems(new String[]{"English","हिन्दी"},(d,i)->{I18n.setLanguage(this,i==0?"en":"hi");home();}).setNegativeButton("Cancel",null).show();}
    private void costs(){PhoneCosts costs=new PhoneCosts(this);I18n.dialog(this).setTitle("Costs").setMessage(costs.summary()).setPositiveButton("Done",null).setNeutralButton("Share record",(d,w)->startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,costs.export()),"Share cost record"))).show();}
    private void latest(){String id=PhoneResearch.get(this).latest();if(id==null){Toast.makeText(this,I18n.text(this,"No recent check on this phone."),Toast.LENGTH_LONG).show();return;}startActivity(new Intent(this,ConsentActivity.class).putExtra("job_id",id).putExtra(EXTRA_SOURCE,"manual"));}
    private void receive(Intent intent){if(intent==null)return;if(intent.getBooleanExtra("open_latest",false)){intent.removeExtra("open_latest");latest();return;}if(!Intent.ACTION_SEND.equals(intent.getAction()))return;
        String type=intent.getType();if(type!=null&&type.startsWith("image/")){Uri uri=intent.getParcelableExtra(Intent.EXTRA_STREAM);intent.removeExtra(Intent.EXTRA_STREAM);intent.setAction(null);if(uri!=null)image(uri);return;}
        String text=intent.getStringExtra(Intent.EXTRA_TEXT);intent.removeExtra(Intent.EXTRA_TEXT);intent.setAction(null);if(text!=null&&!text.trim().isEmpty())startActivity(new Intent(this,ConsentActivity.class).putExtra(EXTRA_TEXT,text).putExtra(EXTRA_SOURCE,"share"));}
    private void image(Uri uri){startActivity(new Intent(this,ImageActivity.class).setData(uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;if(request==12){image(data.getData());return;}if(request==11){try(Cursor cursor=getContentResolver().query(data.getData(),new String[]{ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,ContactsContract.CommonDataKinds.Phone.NUMBER},null,null,null)){if(cursor!=null&&cursor.moveToFirst()){new ChosenContacts(this).add(cursor.getString(0),cursor.getString(1));Toast.makeText(this,I18n.text(this,"Added. Open their WhatsApp chat."),Toast.LENGTH_LONG).show();}}catch(Exception e){Toast.makeText(this,I18n.text(this,"Could not add this person. Please try again."),Toast.LENGTH_LONG).show();}}}
}
