package org.fairc.forwardcheck;

import java.net.InetAddress;
import java.net.URI;
import java.text.Normalizer;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import org.json.JSONObject;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/** Reopens public citations with a deadline; a failed fetch cannot produce a true/false verdict. */
final class SourceVerifier {
    private final OkHttpClient client;
    SourceVerifier(OkHttpClient base) {
        client = base.newBuilder().callTimeout(6, java.util.concurrent.TimeUnit.SECONDS)
                .followRedirects(false).followSslRedirects(false).dns(hostname -> {
                    java.util.List<InetAddress> addresses = java.util.Arrays.asList(InetAddress.getAllByName(hostname));
                    for (InetAddress address : addresses) if (address.isAnyLocalAddress() || address.isLoopbackAddress()
                            || address.isLinkLocalAddress() || address.isSiteLocalAddress() || address.isMulticastAddress()
                            || (address.getAddress().length == 16 && (address.getAddress()[0] & 0xfe) == 0xfc))
                        throw new java.net.UnknownHostException("Private addresses cannot be research sources");
                    return addresses;
                }).build();
    }
    static String normalize(String text) { return Normalizer.normalize(text, Normalizer.Form.NFKC).replaceAll("\\s+", " ").trim(); }
    static boolean publicUrl(String value) {
        try { URI u = URI.create(value); return "https".equalsIgnoreCase(u.getScheme()) && u.getHost() != null
                && u.getUserInfo() == null && (u.getPort() == -1 || u.getPort() == 443); }
        catch (Exception ignored) { return false; }
    }
    private static Instant parseDate(String text) {
        try {return Instant.parse(text);} catch(Exception ignored){}
        try {return OffsetDateTime.parse(text).toInstant();} catch(Exception ignored){}
        return java.time.LocalDate.parse(text.substring(0,10)).atStartOfDay(ZoneOffset.UTC).toInstant();
    }
    String readLink(String url) throws Exception {
        if (!publicUrl(url)) throw new IllegalStateException("Could not open this link. Try pasting the message instead.");
        long deadline=android.os.SystemClock.elapsedRealtime()+6500;
        for(int redirect=0;redirect<3;redirect++) {
            try(Response response=fetch(url,deadline)) {
                if(response.code()>=300&&response.code()<400){String location=response.header("Location");if(location==null)break;url=URI.create(url).resolve(location).toString();if(!publicUrl(url))break;continue;}
                if(!response.isSuccessful()||response.body()==null)break;
                String type=response.header("Content-Type","");if(!type.contains("text/html")&&!type.contains("text/plain"))break;
                Document page=Jsoup.parse(response.peekBody(350000).string(),url);page.select("script,style,noscript,nav,footer,header").remove();
                Element body=page.selectFirst("article,main");String content=(body==null?page:body).text();if(content.length()<100)break;
                return "Linked page title: "+page.title()+"\nRetrieved URL: "+url+"\nUntrusted page text:\n"+content.substring(0,Math.min(14000,content.length()));
            }
        }
        throw new IllegalStateException("Could not open this link. Try pasting the message instead.");
    }
    private Response fetch(String url,long deadline)throws java.io.IOException {
        long remaining=deadline-android.os.SystemClock.elapsedRealtime();
        if(remaining<=0)throw new java.io.InterruptedIOException("Source deadline reached");
        okhttp3.Call call=client.newCall(new Request.Builder().url(url).header("User-Agent","ForwardCheck/0.2").build());
        call.timeout().timeout(remaining,java.util.concurrent.TimeUnit.MILLISECONDS);
        return call.execute();
    }
    JSONObject verifyWithRetrieved(JSONObject item, org.json.JSONArray annotations, boolean recent) {
        // Search excerpts are supplied by the retrieval service, not generated by the model.
        // Current-news freshness still requires a dated source page.
        if (!recent && annotations != null && publicUrl(item.optString("url")) && item.optString("quote").length() >= 20 && item.optString("quote").length() <= 1000) {
            for (int i=0;i<annotations.length();i++) {
                JSONObject annotation=annotations.optJSONObject(i); if(annotation==null)continue;
                JSONObject citation=annotation.optJSONObject("url_citation"); if(citation==null)continue;
                if (!item.optString("url").equals(citation.optString("url")))continue;
                String content=citation.optString("content");
                if(normalize(content).contains(normalize(item.optString("quote")))) try {
                    return new JSONObject().put("source_url",item.getString("url")).put("title",citation.optString("title","Source"))
                            .put("quote",item.getString("quote")).put("published_at","").put("retrieval","search_excerpt");
                } catch(Exception ignored){}
            }
        }
        return verify(item,recent);
    }
    JSONObject verify(JSONObject item, boolean recent) {
        String url = item.optString("url"), quote = item.optString("quote");
        if (!publicUrl(url) || quote.length() < 20 || quote.length() > 1000) return null;
        try {
            long deadline = android.os.SystemClock.elapsedRealtime() + 6500;
            for (int redirects = 0; redirects < 3 && android.os.SystemClock.elapsedRealtime() < deadline; redirects++) {
                try (Response response = fetch(url,deadline)) {
                    if (response.code() >= 300 && response.code() < 400) {
                        String location = response.header("Location"); if (location == null) return null;
                        url = URI.create(url).resolve(location).toString(); if (!publicUrl(url)) return null; continue;
                    }
                    if (!response.isSuccessful() || response.body() == null) return null;
                    String html = response.peekBody(300000).string(); Document page = Jsoup.parse(html, url);
                    String published = "";
                    for (String selector : new String[]{"meta[property=article:published_time]", "meta[itemprop=datePublished]", "meta[name=date]", "time[datetime]"}) {
                        Element meta = page.selectFirst(selector); if (meta != null) { published = meta.hasAttr("content") ? meta.attr("content") : meta.attr("datetime"); break; }
                    }
                    if (published.isEmpty()) {
                        for(Element script:page.select("script[type=application/ld+json]")) {
                            java.util.regex.Matcher date=java.util.regex.Pattern.compile("\"datePublished\"\\s*:\\s*\"([^\"]+)\"").matcher(script.data());
                            if(date.find()){published=date.group(1);break;}
                        }
                    }
                    if (recent) {
                        if (published.isEmpty()) return null;
                        Instant when = parseDate(published);
                        long age = Instant.now().getEpochSecond() - when.getEpochSecond(); if (age < -300 || age > 86400) return null;
                    }
                    page.select("script,style,noscript").remove();
                    if (!normalize(page.text()).contains(normalize(quote))) return null;
                    return new JSONObject().put("source_url", url).put("title", page.title()).put("quote", quote).put("published_at", published);
                }
            }
        } catch (Exception ignored) {}
        return null;
    }
}
