// Representative public-post markup, intercepted locally. These are not live feeds.
export const claim = 'RBI’s announcement for the 22 September 2026 State Government Securities auction puts the aggregate face value on offer at ₹16,750 crore.';
export const hindi = '22 सितंबर 2026 की राज्य सरकारी प्रतिभूतियों की नीलामी के लिए RBI ने कुल अंकित मूल्य 16,750 करोड़ रुपये घोषित किया है।';
const layout = (name, content, dark = false) => `<!doctype html><html><head><meta charset="utf-8"><title>${name} fixture</title><style>body{margin:0;background:${dark ? '#0f1419' : '#f5f7f8'};color:${dark ? '#e7e9ea' : '#172b39'};font:16px/1.55 system-ui}main{width:620px;margin:32px auto}header{font-size:11px;letter-spacing:1px;color:#78899c;margin-bottom:18px}h1{font-size:23px;letter-spacing:-.5px}article[data-testid=tweet],shreddit-post,.thing.link,[data-testid=post-container]{display:block;background:${dark ? '#000' : '#fff'};padding:22px;border:1px solid ${dark ? '#263341' : '#dce3e8'};border-radius:14px;margin:16px 0}a{color:${dark ? '#9cc6ff' : '#286b99'}}.author{font-size:13px;color:#8296ac;margin:0 0 10px}.social{font-size:12px;color:#8296ac;margin-top:15px}</style></head><body><main><header>LAYOUT TEST · LOCALLY SERVED FIXTURE</header><h1>${name}</h1>${content}</main></body></html>`;
export const fixtures = {
  'https://x.com/home': layout('Your feed, with evidence', `<article data-testid="tweet" id="post-one"><div class="author">Example public post · <a href="https://x.com/example/status/100"><time>12m</time></a></div><div data-testid="tweetText">${claim}</div><div class="social"><a href="https://x.com/example/status/100/analytics" aria-label="1,200,000 views">1.2M views</a></div></article><article data-testid="tweet" id="post-two"><div class="author">An opinion, not a news report</div><div data-testid="tweetText">I like rainy evenings and chai.</div></article><div style="height:1300px"></div><article data-testid="tweet" id="offscreen"><div data-testid="tweetText">Off-screen test claim.</div></article>`),
  'https://www.reddit.com/r/india/': layout('r/india · Public posts', `<shreddit-post id="post-one" post-title="${hindi}" post-type="text" score="1400" permalink="/r/india/comments/demo/source/"><div class="author" slot="credit-bar">r/india · Example public post</div><a slot="title" href="/r/india/comments/demo/source/">${hindi}</a><div class="social" slot="buttons">1.4k votes · Discussion</div></shreddit-post><script>customElements.define("shreddit-post",class extends HTMLElement{constructor(){super();this.attachShadow({mode:"closed"}).innerHTML='<slot name="credit-bar"></slot><slot name="title"></slot><slot name="text-body"></slot><slot name="buttons"></slot>';}});</script>`),
  'https://new.reddit.com/r/news/': layout('Reddit · Classic layout', `<div data-testid="post-container" id="post-one"><p class="author">r/news · Example public post</p><h3>${claim}</h3><a data-click-id="comments" href="/r/news/comments/demo/source/">Discussion</a></div>`, true),
  'https://old.reddit.com/r/news/': layout('Old Reddit · Public posts', `<div class="thing link" id="post-one" data-fullname="t3_demo" data-score="1400"><div class="entry"><div class="author">r/news · Example public post</div><a class="title" href="https://example.org/source">${claim}</a><a class="comments" href="/r/news/comments/demo/source/">Comments</a><div class="expando" style="display:none"><div class="usertext-body">HIDDEN TEXT MUST NEVER BE SUBMITTED</div></div></div></div>`)
};
