package org.fairc.forwardcheck.social;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.TemporaryFolder;
import static org.junit.Assert.*;
import java.time.*;
import java.util.*;
import java.lang.reflect.*;
import java.net.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.*;
public class SocialNewsTest {
    @Rule public TemporaryFolder temporary=new TemporaryFolder();
    long now=Instant.parse("2026-09-20T12:00:00Z").toEpochMilli();
    @Test public void oldAndFutureHeadlinesAreNotCurrentEvidence(){assertTrue(SocialNews.fresh("2026-09-20T11:00:00Z",now));assertTrue(SocialNews.fresh("2026-09-19T16:00:00Z",now));assertFalse(SocialNews.fresh("2026-09-19T11:00:00Z",now));assertFalse(SocialNews.fresh("2026-09-21T11:00:00Z",now));assertFalse(SocialNews.fresh("",now));}
    @Test public void bbcPublisherDateAndUrlRequired(){String item=item("Sample science headline only","https://www.bbc.com/news/articles/test","Some factual context.");assertEquals(1,SocialNews.parse(item,now).size());assertEquals(0,SocialNews.parse(item.replace("www.bbc.com","evil.example"),now).size());assertEquals(0,SocialNews.parse(item.replace("20 Sep","19 Sep"),now).size());}
    @Test public void indianFeedUsesActualPublisherUrlAndKeepsLiteralPassage(){String xml=item("India announces a new science mission","https://www.ndtv.com/india-news/science-mission-123","The agency said the launch is planned for next month.");List<SocialVerdict.Source> parsed=SocialNews.parse(xml,now,"https://feeds.feedburner.com/ndtvnews-top-stories");assertEquals(1,parsed.size());SocialVerdict.Source source=parsed.get(0);assertEquals("NDTV: India announces a new science mission",source.title);assertEquals("India announces a new science mission\nThe agency said the launch is planned for next month.",source.quote);assertEquals("2026-09-20T11:00:00Z",source.published);assertEquals(0,SocialNews.parse(xml.replace("www.ndtv.com","ndtv.com.evil.example"),now,"https://feeds.feedburner.com/ndtvnews-top-stories").size());assertEquals(0,SocialNews.parse(xml.replace("https://www.ndtv.com","https://attacker@www.ndtv.com"),now,"https://feeds.feedburner.com/ndtvnews-top-stories").size());assertEquals(0,SocialNews.parse(xml.replace("https://www.ndtv.com","https://www.ndtv.com:444"),now,"https://feeds.feedburner.com/ndtvnews-top-stories").size());}
    @Test public void unknownFeedCannotSmuggleAnArticleHost(){assertEquals(0,SocialNews.parse(item("A sufficiently long headline","https://www.ndtv.com/a","summary"),now,"https://untrusted.example/rss").size());}
    @Test public void warmCacheHitMatchesIitHeadlineWithoutNetwork()throws Exception{SocialNews news=new SocialNews();SocialVerdict.Source source=new SocialVerdict.Source("The Hindu: IIT Bombay faculty member booked for caste abuse, suicide abetment","https://www.thehindu.com/news/national/maharashtra/iit-bombay-faculty-member-booked-for-caste-abuse-suicide-abetment/article71485392.ece","IIT Bombay faculty member booked for caste abuse, suicide abetment\nSahil Wakode, a second-year BTech Energy Science student, was found dead in his hostel on September 18",Instant.now().toString());Field field=SocialNews.class.getDeclaredField("feeds");field.setAccessible(true);((Map<String,List<SocialVerdict.Source>>)field.get(news)).put("fixture",Collections.singletonList(source));long started=System.nanoTime();for(int i=0;i<1_000;i++)assertEquals(1,news.fastRelated("IIT Bombay faculty member booked for caste abuse suicide abetment",20).size());double perLookupMs=(System.nanoTime()-started)/1_000_000.0/1_000;System.out.println("SOCIAL_NEWS_CACHE_HIT_AVG_MS="+perLookupMs);assertTrue("cache lookup should fit UI budget: "+perLookupMs,perLookupMs<20);}
    @Test public void extraCommentaryDoesNotEraseRelevantEvidence()throws Exception{
        SocialNews news=new SocialNews();SocialVerdict.Source source=new SocialVerdict.Source("BBC: Agency launches lunar probe","https://www.bbc.com/news/articles/probe","The agency launches a lunar probe from Florida.",Instant.now().toString());
        Field field=SocialNews.class.getDeclaredField("feeds");field.setAccessible(true);((Map<String,List<SocialVerdict.Source>>)field.get(news)).put("fixture",Collections.singletonList(source));
        assertEquals(1,news.fastRelated("Incredible development for humanity today: the agency launches a lunar probe, another remarkable step demonstrating extraordinary scientific innovation and amazing engineering talent",20).size());
        assertTrue(news.fastRelated("A hospital in Mumbai discovered a new medical treatment",20).isEmpty());
    }
    @Test public void preindexedFullFeedSetFitsFirstLookupBudget()throws Exception{
        SocialNews news=new SocialNews();Method put=SocialNews.class.getDeclaredMethod("put",SocialNews.Feed.class,List.class);put.setAccessible(true);String published=Instant.now().toString();
        for(int feed=0;feed<11;feed++){List<SocialVerdict.Source> sources=new ArrayList<>();for(int item=0;item<80;item++){String quote=feed==10&&item==79?"Agency launches lunar probe from Florida today":"Unrelated market report number "+feed+" item "+item;sources.add(new SocialVerdict.Source("Fixture", "https://www.bbc.com/news/articles/"+feed+"-"+item,quote,published));}put.invoke(news,new SocialNews.Feed("Fixture","https://feed.test/"+feed,"bbc.com"),sources);}
        long started=System.nanoTime();List<SocialVerdict.Source> found=news.fastRelated("The agency launches a lunar probe from Florida today",20);double elapsedMs=(System.nanoTime()-started)/1_000_000.0;System.out.println("SOCIAL_NEWS_FIRST_INDEXED_LOOKUP_MS="+elapsedMs);assertEquals(1,found.size());assertTrue("preindexed lookup should leave most of the 20 ms caller budget: "+elapsedMs,elapsedMs<10);
    }
    @Test public void diskCacheReparsesValidXmlAndRejectsTamperingStalenessAndOversize()throws Exception{
        File cache=temporary.newFolder("rss-cache");ZonedDateTime stamp=ZonedDateTime.now(ZoneOffset.UTC).withNano(0);String rawDate=DateTimeFormatter.RFC_1123_DATE_TIME.format(stamp);
        String xml="<rss><channel><item><title>Agency launches a lunar probe today</title><link>https://publisher.test/news/probe</link><description>The probe launched from Florida.</description><pubDate>"+rawDate+"</pubDate></item></channel></rss>";
        FixtureServer server=server(xml.getBytes(StandardCharsets.UTF_8));ExecutorService firstWorkers=Executors.newSingleThreadExecutor();String endpoint="http://127.0.0.1:"+server.port()+"/rss";SocialNews.Feed feed=new SocialNews.Feed("Fixture",endpoint,"publisher.test");
        try{SocialNews first=new SocialNews(cache,new okhttp3.OkHttpClient(),firstWorkers,feed);first.load(feed);assertEquals(1,first.related("Agency launches lunar probe Florida").size());}finally{firstWorkers.shutdownNow();server.close();}
        File[] files=cache.listFiles((dir,name)->name.endsWith(".xml"));assertNotNull(files);assertEquals(1,files.length);File stored=files[0];
        ExecutorService cachedWorkers=Executors.newSingleThreadExecutor();try{SocialNews cached=new SocialNews(cache,new okhttp3.OkHttpClient(),cachedWorkers,feed);List<SocialVerdict.Source> found=cached.related("Agency launches lunar probe Florida");assertEquals(1,found.size());assertEquals("https://publisher.test/news/probe",found.get(0).url);assertEquals(stamp.toInstant().toString(),found.get(0).published);}finally{cachedWorkers.shutdownNow();}
        try(FileOutputStream out=new FileOutputStream(stored)){out.write(xml.replace("publisher.test","attacker.example").getBytes(StandardCharsets.UTF_8));}stored.setLastModified(System.currentTimeMillis());assertCacheIgnored(cache,feed);
        try(FileOutputStream out=new FileOutputStream(stored)){out.write(new byte[384_001]);}stored.setLastModified(System.currentTimeMillis());assertCacheIgnored(cache,feed);
        try(FileOutputStream out=new FileOutputStream(stored)){out.write(xml.getBytes(StandardCharsets.UTF_8));}assertTrue(stored.setLastModified(System.currentTimeMillis()-86_400_001L));assertCacheIgnored(cache,feed);
    }
    @Test public void actualHttpLoadAcceptsShortFeedAndRejectsOversize()throws Exception{String xml=currentItem("IIT Bombay faculty member booked for caste abuse, suicide abetment","https://publisher.test/news/iit","Sahil Wakode was found dead in his hostel.");FixtureServer shortServer=server(xml.getBytes(StandardCharsets.UTF_8));ExecutorService workers=Executors.newSingleThreadExecutor();try{String endpoint="http://127.0.0.1:"+shortServer.port()+"/rss";SocialNews news=new SocialNews(new okhttp3.OkHttpClient(),workers,new SocialNews.Feed("Fixture",endpoint,"publisher.test"));news.load(new SocialNews.Feed("Fixture",endpoint,"publisher.test"));assertEquals(1,news.related("IIT Bombay faculty booked caste abuse suicide abetment").size());}finally{workers.shutdownNow();shortServer.close();}FixtureServer largeServer=server((xml+"x".repeat(385_000)).getBytes(StandardCharsets.UTF_8));ExecutorService largeWorkers=Executors.newSingleThreadExecutor();try{String endpoint="http://127.0.0.1:"+largeServer.port()+"/rss";SocialNews news=new SocialNews(new okhttp3.OkHttpClient(),largeWorkers,new SocialNews.Feed("Fixture",endpoint,"publisher.test"));news.load(new SocialNews.Feed("Fixture",endpoint,"publisher.test"));assertTrue(news.related("IIT Bombay faculty booked caste abuse suicide abetment").isEmpty());}finally{largeWorkers.shutdownNow();largeServer.close();}}
    private static String item(String title,String link,String description){return "<rss><channel><item><title>"+title+"</title><link>"+link+"</link><description>"+description+"</description><pubDate>Sun, 20 Sep 2026 11:00:00 GMT</pubDate></item></channel></rss>";}
    private static String currentItem(String title,String link,String description){return "<rss><channel><item><title>"+title+"</title><link>"+link+"</link><description>"+description+"</description><pubDate>"+DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now(ZoneOffset.UTC))+"</pubDate></item></channel></rss>";}
    private static FixtureServer server(byte[] body)throws Exception{return new FixtureServer(body);}
    private static void assertCacheIgnored(File cache,SocialNews.Feed feed){ExecutorService workers=Executors.newSingleThreadExecutor();try{SocialNews news=new SocialNews(cache,new okhttp3.OkHttpClient(),workers,feed);assertTrue(news.related("Agency launches lunar probe Florida").isEmpty());}finally{workers.shutdownNow();}}
    private static final class FixtureServer implements AutoCloseable {final ServerSocket server;final Thread thread;FixtureServer(byte[] body)throws Exception{server=new ServerSocket(0,1,InetAddress.getByName("127.0.0.1"));thread=new Thread(()->serve(body));thread.start();}int port(){return server.getLocalPort();}private void serve(byte[] body){try(Socket socket=server.accept()){OutputStream out=socket.getOutputStream();out.write(("HTTP/1.1 200 OK\r\nContent-Type: application/rss+xml\r\nContent-Length: "+body.length+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));out.write(body);out.flush();}catch(Exception ignored){}}public void close()throws Exception{server.close();thread.join(1000);}}
}
