package org.fairc.forwardcheck.social;
import org.junit.Test;
import java.util.*;
import java.nio.charset.StandardCharsets;
import java.io.*;
import static org.junit.Assert.*;
public class SocialRedditOcrTest {
    private static SocialRedditOcr.Line l(String text,int top){return new SocialRedditOcr.Line(text,40,top,940,top+36,96);}
    @Test public void communityCardsKeepOnlyHeadlineBetweenAuthorAndVote(){List<SocialRedditOcr.Line> lines=new ArrayList<>(Arrays.asList(l("r/news",307),l("TOP POSTS ALL TIME",691),l("throwawaynumber53 5y apnews.com",825),l("Joe Biden elected president of the",901),l("United States",956),l("> 365k 28.1k",1146),l("Too_Hood_95 5y kstp.com",1288),l("Chauvin found guilty of murder,",1362),l("manslaughter in George Floyd's death",1419),l("> 250k 27.5k",1609)));lines.set(7,new SocialRedditOcr.Line(lines.get(7).text,40,1419,940,1455,52));List<SocialPost> posts=SocialRedditOcr.community(lines,2157);assertEquals(2,posts.size());assertEquals("Joe Biden elected president of the\nUnited States",posts.get(0).text);assertFalse(posts.get(0).media);assertEquals("Chauvin found guilty of murder,\nmanslaughter in George Floyd's death",posts.get(1).text);assertTrue("uncertain OCR forces closer check",posts.get(1).media);assertFalse(posts.get(0).text.contains("throwaway"));assertFalse(posts.get(0).text.contains("365k"));}
    @Test public void missingCommunityFrameOrVoteNeverParsesArbitraryText(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("user 5y example.com",100),l("The Earth is not flat and has one moon",150),l("> 5k",250));assertTrue(SocialRedditOcr.community(lines,500).isEmpty());List<SocialRedditOcr.Line> cropped=Arrays.asList(l("r/news",20),l("HOT",80),l("user 5y example.com",120),l("The Earth is not flat and has one moon",170));assertTrue(SocialRedditOcr.community(cropped,500).isEmpty());}
    @Test public void communityChevronAndSortIconsAreNotPartOfClaim(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news >",30),l("♧ TOP POSTS ALL TIME v",80),l("user 5y example.com",120),l("Earth has one natural moon.",170),l("> 365k 28.1k",300));assertEquals(1,SocialRedditOcr.extract(lines,1080,600).size());}
    @Test public void numberInHeadlineIsNeverAnEngagementBoundary(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("HOT",80),l("u/author 2h apnews.com",120),l("20k people say the Earth is not flat",170),l("and no one has disproved it",215),l("> 365k 28.1k",300));List<SocialPost> posts=SocialRedditOcr.community(lines,600);assertEquals(1,posts.size());assertEquals("20k people say the Earth is not flat\nand no one has disproved it",posts.get(0).text);}
    @Test public void splitNumericProseIsNeverAnEngagementBoundary(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("HOT",80),l("author 2h apnews.com",120),new SocialRedditOcr.Line("20k",40,170,120,206,96),new SocialRedditOcr.Line("people say the Earth is not flat",260,171,900,207,96),l("and no one has disproved it",215),l("> 365k 28.1k",300));List<SocialPost> posts=SocialRedditOcr.community(lines,600);assertEquals(1,posts.size());assertEquals("20k\npeople say the Earth is not flat\nand no one has disproved it",posts.get(0).text);}
    @Test public void allNumericDateLineIsKeptAsClaimText(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("HOT",80),l("author 2h apnews.com",120),l("The report compares election dates",170),l("2024 2025",215),l("and says the result is NOT final",260),l("> 365k 28.1k",340));List<SocialPost> posts=SocialRedditOcr.community(lines,600);assertEquals(1,posts.size());assertEquals("The report compares election dates\n2024 2025\nand says the result is NOT final",posts.get(0).text);}
    @Test public void uncertainNegationAndAllCapsAreKeptAndForceCloserCheck(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("u/author 2h",100),new SocialRedditOcr.Line("The claim is",40,160,500,196,96),new SocialRedditOcr.Line("not",40,205,120,241,-1),new SocialRedditOcr.Line("NOT TRUE",40,250,300,286,30),l("> 365k 28.1k",320));List<SocialPost> posts=SocialRedditOcr.publicDetail(lines,"r/news",1080,600);assertEquals(1,posts.size());assertEquals("The claim is\nnot\nNOT TRUE",posts.get(0).text);assertTrue(posts.get(0).media);}
    @Test public void splitMlKitToolbarAcceptsIntegerCounts(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",307),l("TOP POSTS ALL TIME",691),l("publicuser 5y apnews.com",825),l("Joe Biden elected president of the",901),l("United States",956),new SocialRedditOcr.Line("7 365k",82,1147,222,1185,96),new SocialRedditOcr.Line("28.1k",476,1152,558,1181,96),new SocialRedditOcr.Line("90",829,1156,864,1180,96));List<SocialPost> posts=SocialRedditOcr.community(lines,2157);assertEquals(1,posts.size());assertEquals("Joe Biden elected president of the\nUnited States",posts.get(0).text);assertEquals(1185,posts.get(0).bottom);}
    @Test public void ocrBubbleOAndLowIntegerCountsEndCard(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("HOT",80),l("author 2h example.com",120),l("The Earth is not flat and has one moon",170),new SocialRedditOcr.Line("12",80,300,120,334,96),new SocialRedditOcr.Line("O 3",470,302,540,336,96));List<SocialPost> posts=SocialRedditOcr.community(lines,600);assertEquals(1,posts.size());assertEquals("The Earth is not flat and has one moon",posts.get(0).text);}
    @Test public void joinedBubbleOEndsCardWithoutBecomingClaimText(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("HOT",80),l("author 2h example.com",120),l("The Earth is not flat and has one moon",170),new SocialRedditOcr.Line("250k O 27.5k",80,300,600,336,96));List<SocialPost> posts=SocialRedditOcr.community(lines,600);assertEquals(1,posts.size());assertFalse(posts.get(0).text.contains("250k"));}
    @Test public void visibleSubredditAllowsScrolledCommunityWithoutSortControl(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",20),l("publicuser 5y apnews.com",120),l("The Earth is not flat and has one moon",170),new SocialRedditOcr.Line("12",80,300,120,334,96),new SocialRedditOcr.Line("3",470,302,510,336,96));assertEquals(1,SocialRedditOcr.extract(lines,1080,600).size());List<SocialRedditOcr.Line> composer=new ArrayList<>(lines);composer.add(l("Create post",60));assertTrue(SocialRedditOcr.extract(composer,1080,600).isEmpty());}
    @Test public void explicitOpenedPostStopsAtFirstVoteBeforeAdOrComments(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("u/user 2h apnews.com",100),l("The Earth is not flat, and it has one moon",160),l("> 365k 28.1k",300),l("An ad that must never become a post",400),l("commenter 1h",500),l("A comment that must never become a post",550));List<SocialPost> posts=SocialRedditOcr.publicDetail(lines,"r/news",1080,600);assertEquals(1,posts.size());assertEquals("The Earth is not flat, and it has one moon",posts.get(0).text);assertEquals(0,posts.get(0).left);assertEquals(1080,posts.get(0).right);assertFalse(posts.get(0).media);assertTrue(SocialRedditOcr.publicDetail(lines,"not a subreddit",600).isEmpty());}
    @Test public void rightThumbnailOcrNeverExtendsDetailClaimOrTextBounds(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("u/user 2h apnews.com",100),l("Joe Biden elected president",160),l("of the United States",205),new SocialRedditOcr.Line("AP ASSOCIATED PRESS",800,165,1040,200),new SocialRedditOcr.Line("apnews.com",800,210,980,240),l("> 365k 28.1k",300));List<SocialPost> posts=SocialRedditOcr.publicDetail(lines,"r/news",1080,600);assertEquals(1,posts.size());assertEquals("Joe Biden elected president\nof the United States",posts.get(0).text);assertEquals(160,posts.get(0).textTop);assertEquals(241,posts.get(0).textBottom);}
    @Test public void bridgeEntryRequiresSubredditThenRecognizesPublicDetail(){List<SocialRedditOcr.Line> lines=Arrays.asList(l("r/news",30),l("u/user 2h apnews.com",100),l("The Earth is not flat, and it has one moon",160),l("> 365k 28.1k",300),l("Comment text must stay out",400));assertEquals(1,SocialRedditOcr.extract(lines,1080,600).size());assertTrue(SocialRedditOcr.extract(lines.subList(1,lines.size()),1080,600).isEmpty());}
    @Test public void selfPostKeepsVisibleBodyAndChatScreenIsRejected(){List<SocialRedditOcr.Line> self=Arrays.asList(l("r/news",30),l("u/author 2h",100),l("The Earth is not flat.",160),l("It has 20k documented observations.",205),l("> 365k 28.1k",300),l("An ad must not be included",400),l("u/commenter 1h",500),l("A comment must not be included",550));List<SocialPost> posts=SocialRedditOcr.publicDetail(self,"r/news",1080,600);assertEquals(1,posts.size());assertEquals("The Earth is not flat.\nIt has 20k documented observations.",posts.get(0).text);List<SocialRedditOcr.Line> chat=new ArrayList<>(self);chat.add(l("Chats",10));assertTrue(SocialRedditOcr.extract(chat,1080,600).isEmpty());}
    @Test public void capturedPublicFixturesKeepOnlyPostTitles()throws Exception{List<SocialPost> cards=SocialRedditOcr.community(SocialRedditOcr.tsv(resource("reddit-community-ocr.tsv")),true,1080,2157);assertEquals(2,cards.size());assertEquals("Joe Biden elected president\nof the United States",cards.get(0).text);assertFalse(cards.get(0).media);assertEquals("Chauvin found guilty of murder,\nmanslaughter in George Floyd's",cards.get(1).text);assertTrue(cards.get(1).media);List<SocialPost> post=SocialRedditOcr.publicDetail(SocialRedditOcr.tsv(resource("reddit-detail-ocr.tsv")),"r/news",1080,2340);assertEquals(1,post.size());assertEquals("Joe Biden elected president\nof the United States",post.get(0).text);assertFalse(post.get(0).media);assertEquals(0,post.get(0).left);assertEquals(1080,post.get(0).right);assertEquals(731,post.get(0).bottom);}
    @Test public void tsvGroupsWordsByOcrLine(){String tsv="level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext\n5\t1\t2\t1\t1\t1\t40\t100\t30\t20\t96\tEarth\n5\t1\t2\t1\t1\t2\t80\t100\t20\t20\t90\tis\n5\t1\t2\t1\t1\t3\t110\t100\t30\t20\t95\tnot";List<SocialRedditOcr.Line> lines=SocialRedditOcr.tsv(tsv);assertEquals(1,lines.size());assertEquals("Earth is not",lines.get(0).text);assertEquals(40,lines.get(0).left);}
    private static String resource(String name)throws Exception{InputStream input=SocialRedditOcrTest.class.getResourceAsStream("/social/"+name);assertNotNull("missing fixture "+name,input);try(BufferedReader reader=new BufferedReader(new InputStreamReader(input,StandardCharsets.UTF_8))){StringBuilder out=new StringBuilder();String line;while((line=reader.readLine())!=null)out.append(line).append('\n');return out.toString();}}
}
