(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const token=(document.querySelector('meta[name="local-pair-token"]')||{}).content||"";
  const state={dashboard:null,scope:"live_feed",pollTimer:null};
  const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined&&text!==null)node.textContent=String(text);if(className)node.className=className;return node};
  const number=value=>Number.isFinite(Number(value))?Number(value):0;
  const count=value=>new Intl.NumberFormat("en-US",{notation:number(value)>=1000000?"compact":"standard",maximumFractionDigits:1}).format(number(value));
  const money=value=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:number(value)<100?2:0}).format(number(value));
  const percent=value=>{let n=number(value);if(n>0&&n<=1)n*=100;return n.toFixed(n<10&&n!==0?1:0)+"%"};
  const words=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
  async function api(path,options={}){const headers=Object.assign({},options.headers||{}, {"X-Factcheck-Token":token});const response=await fetch(path,Object.assign({},options,{headers}));let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.detail||body.error||"Local service returned "+response.status);return body}
  function safeLink(title,url){const a=el("a",title||"Open source");try{const parsed=new URL(url,location.origin);if(parsed.protocol==="http:"||parsed.protocol==="https:"){a.href=parsed.href;a.target="_blank";a.rel="noopener noreferrer"}}catch{}return a}

  document.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",()=>showTab(button.dataset.tab)));
  function showTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===id));history.replaceState(null,"","#"+id);window.scrollTo({top:0,behavior:"smooth"})}
  const initialTab=location.hash.slice(1);if(["overview","hierarchy","activity","costs"].includes(initialTab))showTab(initialTab);
  document.querySelectorAll("[data-scope]").forEach(button=>button.addEventListener("click",()=>{state.scope=button.dataset.scope;document.querySelectorAll("[data-scope]").forEach(x=>x.classList.toggle("active",x===button));renderMetrics()}));

  async function loadDashboard(){try{const data=await api("/api/dashboard");state.dashboard=data||{};$("system-dot").classList.toggle("ready",data.model_ready===true);$("system-label").textContent=data.model_ready?"Local model ready":"Index ready · model warming";renderDashboard()}catch(error){$("system-label").textContent="Local service unavailable";renderWarnings([error.message])}}
  function renderDashboard(){const d=state.dashboard||{},stats=d.stats||{},index=d.index||{};$("index-count").textContent=count(index.passages??index.documents??stats.sources??0);$("investigation-count").textContent=count(stats.investigations);$("spend-count").textContent=money(stats.paid_api_spend);renderWarnings(d.warnings||[]);renderMetrics();renderExamples(d.examples||[]);renderHierarchy(d.events||[],d.claims||[]);renderRoutes(stats.routes||{});renderRecent(d.recent||[])}
  function renderWarnings(items){const box=$("warnings");box.replaceChildren();box.hidden=!items.length;items.forEach(item=>box.append(el("p",typeof item==="string"?item:(item.message||item.detail||"Dashboard warning"))))}
  function renderMetrics(){const stats=((state.dashboard||{}).stats||{})[state.scope]||{};const observed=number(stats.observed),assessed=number(stats.assessed),decisive=number(stats.decisive),pre=number(stats.prelabelled);const coverage=stats.coverage!=null?stats.coverage:(observed?decisive/observed:0);const cachedCoverage=stats.prelabelled_coverage!=null?stats.prelabelled_coverage:(observed?pre/observed:0);$("m-coverage").textContent=observed?percent(coverage):"—";$("m-coverage-detail").textContent=count(decisive)+" decisive / "+count(observed)+" observed";$("m-observed").textContent=count(observed);$("m-prelabelled").textContent=count(pre);$("m-prelabelled-detail").textContent=observed?percent(cachedCoverage)+" of observed posts":"Available at first view";$("m-new").textContent=count(Math.max(0,assessed-pre));$("m-unsure").textContent=count(Math.max(0,assessed-decisive));$("scope-note").textContent=state.scope==="live_feed"?"Distinct visible post versions captured with consent. Development examples never enter this denominator.":"Recorded replays, synthetic robustness cases, and explicit dashboard checks. These figures do not describe live-feed coverage."}
  function renderExamples(examples){const box=$("examples");box.replaceChildren();examples.slice(0,6).forEach(example=>{const button=el("button",example.title||"Replay example");button.type="button";button.title=example.description||"Source-derived development example";button.addEventListener("click",()=>{$("post-text").value=example.text||"";$("has-media").checked=example.has_media===true;const post=example.post||{};$("relation").value=["original","repost","quote","copy"].includes(post.relation)?post.relation:"original";$("original-id").value=post.original_post_id||"";$("post-id").value=post.post_id||"";$("quoted-text").value=post.quoted_text||"";$("post-text").focus()});box.append(button)});if(!examples.length)box.append(el("span","No recorded examples loaded","subtle"))}
  function renderHierarchy(events,claims){const box=$("hierarchy-list");box.replaceChildren();if(!events.length&&!claims.length){box.append(el("p","No indexed political events are available yet.","empty-list"));return}const topics=new Map();events.forEach(event=>{const topic=event.topic||"Politics";if(!topics.has(topic))topics.set(topic,[]);topics.get(topic).push(event)});topics.forEach((topicEvents,topic)=>{const topicRow=treeRow(topic,"Topic · routing context only",topicEvents.length,"topic");topicRow.addEventListener("click",()=>renderDetail("topic",{title:topic,event_count:topicEvents.length,claim_count:topicEvents.reduce((n,e)=>n+number(e.claim_count),0),post_count:topicEvents.reduce((n,e)=>n+number(e.post_count),0)}));box.append(topicRow);const eventGroup=el("div",null,"event-children");topicEvents.forEach(event=>{const row=treeRow(event.title||event.id,"Event · "+count(event.claim_count)+" claims · "+count(event.post_count)+" post versions",event.post_count||event.claim_count,"event");row.addEventListener("click",()=>renderDetail("event",event));eventGroup.append(row);const children=el("div",null,"tree-children");claims.filter(c=>String(c.event_id)===String(event.id)).forEach(claim=>{const status=claim.stale?"Expired / needs recheck":words(claim.status||"unresolved");const claimRow=treeRow(claim.text||claim.id,status+" · "+count(claim.source_count)+" sources · "+count(claim.post_count)+" versions",claim.post_count,"claim");claimRow.addEventListener("click",()=>renderDetail("claim",claim));children.append(claimRow)});eventGroup.append(children)});box.append(eventGroup)})}
  function treeRow(title,meta,total,type){const button=el("button",null,"tree-row");button.type="button";button.append(el("i",null,"node-dot"));const copy=el("span");copy.append(el("span",title,"node-title"),el("span",meta,"node-meta"));button.append(copy,el("span",count(total),"count"));button.dataset.type=type;return button}
  function renderDetail(type,item){const box=$("hierarchy-detail");box.replaceChildren(el("p",type,"kicker"),el("h2",type==="claim"?"Canonical assertion":(item.title||"Event")));if(type==="claim"){box.append(el("p",item.text||"No text available","claim-copy"));if(item.stale)box.append(el("p","Expired / needs recheck. The status below is historical and must not be treated as a current assessment.","citation"))}const facts=type==="claim"?[["Status",item.stale?"Expired / needs recheck":words(item.status||"unresolved")],["Post versions / reuse",count(item.post_count)],["Source passages",count(item.source_count)],[item.stale?"Previously checked":"Last checked",formatDate(item.checked_at)]]:type==="topic"?[["Events",count(item.event_count)],["Canonical claims",count(item.claim_count)],["Post versions",count(item.post_count)],["Role","Routing context only"]]:[["Canonical claims",count(item.claim_count)],["Post versions",count(item.post_count)],["Topic",item.topic||"Politics"]];facts.forEach(pair=>{const row=el("div",null,"fact-row");row.append(el("span",pair[0]),el("strong",pair[1]));box.append(row)});if(type==="claim")renderPostVersions(box,item.post_versions||[])}
  function renderPostVersions(box,versions){if(!versions.length)return;const nativeLinks=versions.filter(version=>version.relation==="native_repost"&&version.original_post_id);box.append(el("p","Checked post versions","kicker"));if(nativeLinks.length)box.append(el("p",count(nativeLinks.length)+" native repost "+(nativeLinks.length===1?"edge":"edges")+" linked to an original post ID.","subtle"));versions.slice(0,12).forEach(version=>{const card=el("div",null,"citation");const relation=words(version.relation||"unknown");const identity=[version.platform,version.post_id].filter(Boolean).join(" · ")||"Stored post version";card.append(el("strong",identity),el("p",(version.text||"Text unavailable").slice(0,240)));let meta=relation+" · "+formatDate(version.created_at);if(version.relation==="native_repost"&&version.original_post_id)meta+=" · original → "+version.original_post_id;card.append(el("small",meta,"subtle"));box.append(card)})}
  const routeLabels={exact_reuse:"Exact version",unchanged_repost:"Unchanged repost",claim_reuse:"Claim reuse",evidence_reuse:"Evidence reuse",fresh_review:"Fresh review",abstained:"Abstained"};
  function renderRoutes(routes){const box=$("route-grid");box.replaceChildren();Object.keys(routeLabels).forEach(key=>{const card=el("div",null,"route-stat");card.append(el("span",routeLabels[key]),el("strong",count(routes[key])));box.append(card)})}
  function renderRecent(items){const box=$("recent-list");box.replaceChildren();if(!items.length){box.append(el("p","No development assessments recorded yet.","empty-list"));return}items.slice(0,12).forEach(item=>{const row=el("div",null,"recent-item");const rating=el("span",item.label||words(item.rating||"unresolved"),"recent-rating");const copy=el("div",item.text||"Untitled assessment","recent-text");const reuse=item.reuse&&typeof item.reuse==="object"?item.reuse.kind:item.reuse;copy.append(el("small",words(reuse||"fresh_review")+" · "+words(item.capture_scope||item.scope||"development")));row.append(rating,copy,el("time",formatDate(item.checked_at),"recent-time"));box.append(row)})}
  function formatDate(value){if(!value)return "—";const raw=typeof value==="number"&&value<1e12?value*1000:value;const d=new Date(raw);return Number.isNaN(d.valueOf())?String(value):new Intl.DateTimeFormat("en",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(d)}

  $("check-button").addEventListener("click",submitCheck);
  async function submitCheck(){const text=$("post-text").value.trim();if(text.length<3){$("post-text").focus();return}const selectedRelation=$("relation").value;const relation={original:"unknown",repost:"native_repost",quote:"quote",copy:"unknown"}[selectedRelation]||"unknown";const quotedText=$("quoted-text").value.trim();const post={platform:"demo",post_id:$("post-id").value.trim()||undefined,published_at:$("published-at").value||undefined,original_post_id:$("original-id").value.trim()||undefined,relation,quoted_text:quotedText||undefined,has_commentary:selectedRelation==="quote"&&Boolean(text),media_fingerprint:undefined};Object.keys(post).forEach(key=>post[key]===undefined&&delete post[key]);const payload={text,has_media:$("has-media").checked,post,scope:"development",session_id:getSessionId(),observation_id:"dash-"+Date.now()};$("check-button").disabled=true;renderLoading("Submitting development check…");try{try{await api("/api/observations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:payload.session_id,observation_id:payload.observation_id,platform:"demo",text,has_media:payload.has_media,has_quoted_content:selectedRelation==="quote"||Boolean(quotedText),scope:"development"})})}catch{}const submitted=await api("/api/check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await pollJob(submitted.job_id,submitted.cached===true)}catch(error){renderError(error.message)}finally{$("check-button").disabled=false}}
  function getSessionId(){let id=sessionStorage.getItem("signal-desk-session");if(!id){id="dashboard-"+Date.now()+"-"+Math.random().toString(36).slice(2);sessionStorage.setItem("signal-desk-session",id)}return id}
  async function pollJob(jobId,cached){for(let attempt=0;attempt<240;attempt++){const job=await api("/api/jobs/"+encodeURIComponent(jobId));if(job.status&&job.status!=="pending"&&job.status!=="queued"&&job.status!=="running"){if(job.status==="complete"){renderResult(job.result||{},cached);loadDashboard()}else renderError(job.error||"The review did not complete.");return}renderLoading(job.stage||"Checking source passages…");await new Promise(resolve=>state.pollTimer=setTimeout(resolve,900))}throw new Error("The check is still running. Try again shortly.")}
  function renderLoading(stage){const card=$("result-card");card.setAttribute("aria-busy","true");card.replaceChildren();const wrap=el("div",null,"loading-result");wrap.append(el("p","Evidence review","kicker"),el("h2",stage),el("div",null,"loading-bar"),el("p","The pipeline is resolving the post version, retrieving passages, and checking the precise assertion.","subtle"));wrap.querySelector(".loading-bar").append(el("i"));card.append(wrap)}
  function renderError(message){const card=$("result-card");card.setAttribute("aria-busy","false");card.replaceChildren();const wrap=el("div",null,"empty-result");wrap.append(el("p","Check unavailable","kicker"),el("h2","No result was published."),el("p",message||"The local checker could not complete this review."));card.append(wrap)}
  function renderResult(result,cached){const card=$("result-card");card.setAttribute("aria-busy","false");card.replaceChildren();appendAssessment(card,result,cached,"Current post assessment");if(result.original_assessment){const divider=el("div",null,"claim-result");divider.append(el("p","Quoted or reposted original · separate scope","kicker"),el("p","This assessment applies only to the referenced original. It does not rate the current post's wrapper commentary.","subtle"));card.append(divider);appendAssessment(card,result.original_assessment,true,"Original assessment")}}
  function appendAssessment(card,result,cached,title){const top=el("div",null,"result-top"),heading=el("div");const label=result.label||"Unresolved";const rating=number(result.rating);const verdictClass=rating===4||/support|true/i.test(label)?"supported":rating===2||/contradict|false/i.test(label)?"contradicted":"unsure";const reuse=result.reuse&&typeof result.reuse==="object"?result.reuse:{};const routeKind=reuse.kind||result.route||(cached?"exact_reuse":"fresh_review");heading.append(el("p",title+" · "+words(result.scope||"development"),"kicker"),el("div",label,"verdict "+verdictClass));top.append(heading,el("span",words(routeKind),"route"));card.append(top,el("p",result.summary||result.explanation||reuse.reason||(cached?"Returned from a previously checked version.":"Checked against the available evidence passages."),"result-summary"));if(reuse.reason&&(result.summary||result.explanation))card.append(el("p","Reuse: "+reuse.reason,"result-summary"));const claims=Array.isArray(result.claims)?result.claims:[];claims.forEach(claim=>{const section=el("section",null,"claim-result");const verdict=claim.verdict||claim.label||"insufficient_evidence";const cls=/^supported$/i.test(verdict)?"supported":/^contradicted$/i.test(verdict)?"contradicted":"unsure";section.append(el("span",words(verdict),"claim-status "+cls),el("h3",claim.text||"Claim"));const evidence=Array.isArray(claim.evidence)?claim.evidence:[];evidence.forEach(source=>{const cite=el("div",null,"citation");cite.append(el("blockquote",source.quote||source.passage||source.text||"Source passage unavailable"),safeLink(source.title||source.source_title||"Source",source.source_url||source.url||""));section.append(cite)});if(!evidence.length)section.append(el("p","No decisive passage was available for this claim.","subtle"));card.append(section)});if(!claims.length)card.append(el("p","No externally checkable factual assertion was resolved in this scope.","subtle"))}

  ["cost-initial","cost-daily","cost-search-share","cost-model-share","cost-x-initial","cost-x-daily"].forEach(id=>$(id).addEventListener("input",calculateCosts));
  function calculateCosts(){const value=id=>Math.max(0,number($(id).value));const initial=value("cost-initial"),daily=value("cost-daily"),searchShare=Math.min(100,value("cost-search-share"))/100,modelShare=Math.min(100,value("cost-model-share"))/100,xInitial=value("cost-x-initial"),xDaily=value("cost-x-daily");const search=6*.005,review=20000*3/1000000+3000*15/1000000;const attempt=1.25*(searchShare*search+modelShare*review);const startResearch=initial*attempt,dailyResearch=daily*attempt,startX=xInitial*.005,dailyX=xDaily*.005;$("startup-research").textContent=money(startResearch);$("daily-research").textContent=money(dailyResearch);$("startup-x").textContent=money(startX);$("daily-x").textContent=money(dailyX);$("startup-total").textContent=money(startResearch+startX);$("daily-total").textContent=money(dailyResearch+dailyX);const note=$("x-limit-note");note.hidden=xDaily*30<=3000000;note.textContent="At this daily volume, 30 days exceeds the published 3M self-service monthly read allowance. An enterprise quote may be required."}
  calculateCosts();loadDashboard();
})();
